### ISSUE TITLE
Broken link to astro js

### ISSUE THREAD

**Issue by 6TELOIV** [mejiaj/mejiaj#77]
**Describe the bug**
Your link in your colophon page for astro seems to be broken. Link is for astro.js but the real URL is astro.build

**To Reproduce**
1. Go to [https://www.jmejia.com/colophon/](https://www.jmejia.com/colophon/)
2. Click on [https://astro.js/](https://astro.js/)

**Additional context**
I wish .js was a valid tld. how cool would that be!

**Comment by mejiaj** [comment]
That _would_ be cool. Thanks for pointing the broken link out and creating the issue!
